### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by ShridharCodewave** [busfor/react-native-google-pay#1]
Iam using this library in my react native project. The app is running in debug mode but Iam not able to generate the signed apk as Iam getting the following error log every time

>Execution failed for task ':react-native-google-pay:verifyReleaseResources'.
 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
  error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:7: error: resource android:attr/colorError not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:11: error: resource android:attr/colorError not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values\values.xml:2807: error: resource android:attr/fontStyle not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values\values.xml:2808: error: resource android:attr/font not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values\values.xml:2809: error: resource android:attr/fontWeight not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values\values.xml:2810: error: resource android:attr/fontVariationSettings not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values\values.xml:2811: error: resource android:attr/ttcIndex not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values\values.xml:2892: error: resource android:attr/startX not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values\values.xml:2895: error: resource android:attr/startY not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values\values.xml:2898: error: resource android:attr/endX not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values\values.xml:2901: error: resource android:attr/endY not found.
  F:\React Native Projects\sampleApp\node_modules\react-native-google-pay\android\build\intermediates\res\merged\release\values\values.xml:2909: error: resource android:attr/offset not found.
  error: failed linking references.

Package.json

> "react-native": "0.59.8",
"react-native-google-pay": "^1.2.0",

Project level build.gradle

`buildscript` {

    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

Gradle wrapper properties

> distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

**Comment by sorokin0andrey** [comment]
Hello @ShridharCodewave ! Try to build signed apk with `./gradlew app:assembleRelease`

**Comment by ShridharCodewave** [comment]
@sorokin0andrey Iam using the same method. Its giving the same error every time.

**Comment by MatthewPattell** [comment]
Hi @ShridharCodewave, try this (android/build.gradle):
```
subprojects { subproject ->
    afterEvaluate {
        if ((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}
```

**Comment by ShridharCodewave** [comment]
Hi @MatthewPattell Thank you for the solution its working.
