### ISSUE TITLE
ReactNative: [GooglePay] Not available

### ISSUE THREAD

**Issue by daijiangping** [busfor/react-native-google-pay#10]
ReactNative: [GooglePay] Not available

**Comment by isokolovskii** [comment]
@daijiangping It may happen if GooglePay is not available on device. 

Can you give more detailed description of a problem - like situation(or better code example) when it happened, device manufacturer and model, Android version etc.?

**Comment by okechukwu0127** [comment]
Just experience this issue on my end

After successfull configurating of the module (Llinking and AndroidManuscript)
i get this error on the Log. Nothing happens after button click. All i have is a log
RN: 0.59.8
Device: Infinix Zero 5Pro


Did a little digging into the module and got the error been flagged on **isReadyToPay** method
![image](https://user-images.githubusercontent.com/23473673/81478913-2a040b80-9218-11ea-9a5c-ff1b5880d80a.png)


Kindly assist in the issue or tell me what to do.

Regards
