### ISSUE TITLE
React Native: Google-pay Not Ready

### ISSUE THREAD

**Issue by Farhandroid** [busfor/react-native-google-pay#11]
I just followed your instruction and used code from your example . But it always said that Google Pay is not ready . I just put an alert to find the error . ''ready always return false' . I am using android 9.0 and react native 0.60.0.
![GooglePayIsNotReady](https://user-images.githubusercontent.com/32593150/67933862-0b3e1000-fc0a-11e9-9f60-e68a11aaf465.PNG)

**Comment by JollyGolf** [comment]
You are sure that Google Pay is available on your device?

**Comment by karthikcodes6** [comment]
Same problem @Farhandroid did you solved the problem?

**Comment by chetanparmar95** [comment]
Facing same issue. value of `ready`  is always false. Tested on real device also with google pay installed.

**Comment by Zhigamovsky** [comment]
Please, check your `allowedCardNetworks` and `allowedCardAuthMethods`. In my case, I used: `const allowedCardNetworks = ['VISA', 'MASTERCARD'];
  const allowedCardAuthMethods = ['PAN_ONLY', 'CRYPTOGRAM_3DS'];` and all works fine with this params. I tested on React Native 0.61.5 and react-native-google-pay ^2.1.0. Tested on Android Emulator (android 7+, include versions 9.0, 10.0), tested on real device (android 7+, include versions 9.0, 10.0). And I successfully released my app at Google Play, all works fine.

If you have some questions, I will be happy to help.

**Comment by tuladharjaa** [comment]
I also have the same problem. I have Google Pay installed on my phone.
