### ISSUE TITLE
Working on Android Q but not in Pie

### ISSUE THREAD

**Issue by Farhandroid** [busfor/react-native-google-pay#12]
I have followed your every instruction . But  it works on Android Q but not in Pie .

**Comment by Jalson1982** [comment]
Any solution?

**Comment by sorokin0andrey** [comment]
Hello! Could you give more information about your problem? What is the error?

**Comment by Jalson1982** [comment]
GooglePay.isReadyToPay(allowedCardNetworks, allowedCardAuthMethods)
  .then((ready) => {
    if (ready) {
      console.log(ready,"ready")
      GooglePay.requestPayment(requestData)
        .then((token: string) => {
          // Send a token to your payment gateway
        })
        .catch((error) => console.log(error.code, error.message));
    }
  })
 When you run for example this code, nothing happens. I can not see any error on logcat or something. Hard to say what is wrong. I only get it to work on android nexus simulator.

**Comment by JollyGolf** [comment]
You are sure that Google Pay is available on your device?

**Comment by sorokin0andrey** [comment]
Duplicate of #16
