### ISSUE TITLE
Cannot read property 'setEnvironment' of undefined

### ISSUE THREAD

**Issue by CezarCobuz** [busfor/react-native-google-pay#14]
Getting the error:

> TypeError: Cannot read property 'setEnvironment' of undefined

on the following line: 
```
// Set the environment before the payment request
  GooglePay.setEnvironment(GooglePay.ENVIRONMENT_TEST);
```
How can I solve this? Has anyone else bumped into this problem?

**Comment by sorokin0andrey** [comment]
@CezarCobuz Have you solved your problem?

**Comment by andrew528i** [comment]
Had the same promblem. `watchman watch-del-all` and re-renning `react-native run-android` solved it for me

**Comment by JollyGolf** [comment]
I had the same problem. Just 'clean and rebuild'. Or check if library properly linked and try linking manually.

Close the issue, if it helped you.
