### ISSUE TITLE
GooglePay not available!

### ISSUE THREAD

**Issue by Jalson1982** [busfor/react-native-google-pay#16]
Hello. I tried to add your lib into my project and also try to start your demo but without success. What is the issue. You have in the demo also this code:

payWithGooglePay = (requestData: RequestDataType) => {
    // Check if Google Pay is available
    GooglePay.isReadyToPay(allowedCardNetworks, allowedCardAuthMethods).then((ready) => {
      if (ready) {
        // Request payment token
        GooglePay.requestPayment(requestData)
          .then(this.handleSuccess)
          .catch(this.handleError)
      }
    })
  }

GooglePay.isReadyToPay never runs on real device! On the simulator, ok but on a real device, it does not run.  I have google pay installed on my different phones and linked credit cards I use for payment but here it does not show even error nothing happens at all. You can easily test this out on any android real device.

**Comment by Jalson1982** [comment]
In logcat android studio i see this error:
[GooglePay] Not available
<img width="876" alt="Screenshot 2020-02-19 at 14 02 50" src="https://user-images.githubusercontent.com/35011526/74836851-85f97b00-5320-11ea-8035-4091827bd433.png">

**Comment by Jalson1982** [comment]
Tried different mobile devices Huawei P20 Pro, Samsung s10, Bluboo Maya Max - 6.0 always the same error. I tried other apps that accept google pay ( wish for example ) my google pay is working so that is not an issue.

**Comment by sorokin0andrey** [comment]
@Jalson1982 Hello! Have you resolved your problem?

**Comment by okechukwu0127** [comment]
I also have this problem just now.
Every setup was properly done as regard to linking and AndroidManifest meta value been added.

Application runs properly but when i click on my Gpay button, nothing happens. 
All i see is a log saying **ReactNative: [GooglePay] Not available**

What am i not doing right ?

**Comment by keving-vargasb** [comment]
I think it has to do with the availability of google pay in certain countries
