### ISSUE TITLE
How to Handle Response

### ISSUE THREAD

**Issue by affanhashone** [busfor/react-native-google-pay#2]
How to Handle Response when payment is success there is no response url ?
in response token i get **exampleTokenrequest**

**Comment by sorokin0andrey** [comment]
> in response token i get **exampleTokenrequest**

That's right, because you use test data in response comes a test token. You need to enter the details of your payment gateway and send it the received token for payment.

**Comment by affanhashone** [comment]
Okay Thank You,  But is this right way to pass the data:




const requestData = {
            cardPaymentMethod: {
              tokenizationSpecification: {
                type: 'PAYMENT_GATEWAY',
                gateway: 'stripe',
                gatewayMerchantId: '****',              
                "stripe:publishableKey": "******",
                "stripe:version": "5.1.0"
        
              },
              allowedCardNetworks,
              allowedCardAuthMethods,
            },
            transaction: {
              totalPrice: "*****",
              totalPriceStatus: 'FINAL',
              currencyCode: 'USD',
            },
            merchantName: '********',
          };

I am using Stripe,its gives me error : Error in loadPaymentData: Field: stripe:version is missing

**Comment by sorokin0andrey** [comment]
@affanhashone added support for stripe in version 1.3.0
Please check and give feedback

**Comment by affanhashone** [comment]
@sorokin0andrey Thanks Buddy, Its Working, Thanks You For Quick Support

**Comment by sorokin0andrey** [comment]
@affanhashone you are welcome :)
