### ISSUE TITLE
Error. Payment data

### ISSUE THREAD

**Issue by seriklav** [busfor/react-native-google-pay#21]
<img width="765" alt="GPAy" src="https://user-images.githubusercontent.com/5691789/90953169-cc679800-e471-11ea-9e11-8ec2603dabf8.png">
I have next error.
can you please help ?

**Comment by sorokin0andrey** [comment]
@seriklav Hi! Do you still have that problem? If so, could you describe that case and send more information? Otherwise, i will close this issue. Thanks!

**Comment by seriklav** [comment]
all is ok, i am settings google payment account connect my payment system and all works fine.
