### ISSUE TITLE
There are no acceptable cards available for use with this merchant.

### ISSUE THREAD

**Issue by sallu00** [busfor/react-native-google-pay#22]
- I have already a VISA card linked to my google pay account, still getting this issue.

Is anybody knows this issue ?

Thanks in advance

**Comment by qtrgq** [comment]
The same issue. 

@sallu00 Did you resolve it ?

**Comment by sallu00** [comment]
@trigsen It was only working for US Cards only, so to test this you can create the APK and then test this.
