### ISSUE TITLE
Card type not found , try another card

### ISSUE THREAD

**Issue by rajatbhatia1998** [busfor/react-native-google-pay#26]
I am facing some issues while adding card in payment screen, It is showing some error like VALID CARD TYPE NOT FOUND , TRY ANOTHER CARD.

 I am using {gateway,merchantId} in requestData 

Can anyone help me regarding this issue , is there any configuration I missed ?

Thanks in Advance

**Comment by sorokin0andrey** [comment]
Hi, @rajatbhatia1998 ! Did you add the type of your card to `allowedCardNetworks`?
