### ISSUE TITLE
Tokenization and Merchant Initiated Transactions

### ISSUE THREAD

**Issue by neiker** [busfor/react-native-google-pay#29]
It is possible to tokenize a payment method to charge the user at the end of the month a variable amount depending of the consuming of that month?

I'm using Adyen as payment provider
https://docs.adyen.com/online-payments/tokenization

**Comment by sorokin0andrey** [comment]
Hello, @neiker ! You should use a token immediately because it has expiration time. As i understood, you wanna do something like subscription. In that case you should use [react-native-iap](https://github.com/dooboolab/react-native-iap) module.

**Comment by neiker** [comment]
Hi @sorokin0andrey , thanks for your answer! 
IAP will not work in my case because I don't know the price until the end of the month. Is a parking app, the user can park their car wherever they want and at the end of the month all parking events will be charged at once. Because of this every month the amount will be different and even in some months it will be zero.
