### ISSUE TITLE
Doesn't work on real device

### ISSUE THREAD

**Issue by GFean** [busfor/react-native-google-pay#30]
Works fine in simulator. On the real device it doesn't have a reaction when clicking on the button.

**Comment by sorokin0andrey** [comment]
Hi! GPay doesn’t work in development environment on real devices. Also you might forgot to set environment to ENVIRONMENT_PRODUCTION:

```typescript
// Set the environment before the payment request
GooglePay.setEnvironment(GooglePay.ENVIRONMENT_PRODUCTION);
```

**Comment by LarysaMatsirka** [comment]
@sorokin0andrey, does it mean that in case of testing on the real device (doesn't matter for STAGE or PROD environment) it needs to set GooglePay.ENVIRONMENT_PRODUCTION as the used environment?
