### ISSUE TITLE
There are no accepted cards available for use with this merchant

### ISSUE THREAD

**Issue by vibdheeraj** [busfor/react-native-google-pay#6]
` const allowedCardNetworks = ['VISA', 'MASTERCARD'];
    const allowedCardAuthMethods = ['PAN_ONLY', 'CRYPTOGRAM_3DS'];
    const device_supported = await stripe.deviceSupportsAndroidPay();
    const can_make_android_pay_payments = await stripe.canMakeAndroidPayPayments();
    const requestData = {
      cardPaymentMethod: {
        tokenizationSpecification: {
          type: 'PAYMENT_GATEWAY',
          // stripe (see Example):
          gateway: 'stripe',
          gatewayMerchantId: '',
          stripe: {
            publishableKey: 'pk_test_xxxxx1mxjhZ8R1dsVBVjzOFm00Wxxxxxxx',
            version: '2018-11-08',
          },
          // other:
          
        },
        allowedCardNetworks,
        allowedCardAuthMethods,
      },
      transaction: {
        totalPrice: '10',
        totalPriceStatus: 'FINAL',
        currencyCode: 'USD',
      },
      merchantName: 'Example Merchant',
    };
    GooglePay.setEnvironment(GooglePay.ENVIRONMENT_TEST);
    GooglePay.isReadyToPay(allowedCardNetworks, allowedCardAuthMethods)
  .then((ready) => {
    if (ready) {
      // Request payment token
      GooglePay.requestPayment(requestData)
        .then((token) => {
          // Send a token to your payment gateway
        })
        .catch((error) => console.log(error.code, error.message));
    }
  })
    console.log("ressssssssss",JSON.stringify(device_supported))
    console.log("ressssssssss",JSON.stringify(can_make_android_pay_payments))
    try {
      const token = await stripe.paymentRequestWithNativePay({
        total_price: this.state.item.price.toFixed(2),
        currency_code: this.state.currency_code,
        shipping_address_required: true,
        line_items: [
          {
            currency_code: this.state.currency_code,
            description: this.state.item.title,
            total_price: this.state.item.price.toFixed(2),
            unit_price: this.state.item.price.toFixed(2),
            quantity: '1',
          }
        ],

      });
    }catch(e){
      console.log("error getting token: ", e);
    }
    console.log("ressssssssss",JSON.stringify(token))`

**Comment by dharmeshsharma** [comment]
Hii got any solution?

**Comment by vibdheeraj** [comment]
not yet

**Comment by isokolovskii** [comment]
@vibdheeraj can you please provide more detailed description of your issue, what errors happens, which workflow brings you to error and a sample code to reproduce

**Comment by sorokin0andrey** [comment]
stale

**Comment by surajit-2908** [comment]
hello.. got any solution? I'm facing the same problem.

**Comment by surajit-2908** [comment]
It's solved. If the user-added valid payment method in google payment center then it would show.

https://pay.google.com/gp/w/u/0/home/paymentmethods

**Comment by sailywebvillee** [comment]
Hello @surajit-2908 Can you help me I am also stuck with the same issue. So can you let me know what exactly you have added?

**Comment by surajit-2908** [comment]
> Hello @surajit-2908 Can you help me I am also stuck with the same issue. So can you let me know what exactly you have added?

You've to add your credit card details in the google payment method.
