### ISSUE TITLE
DIrect Payment Method

### ISSUE THREAD

**Issue by affanhashone** [busfor/react-native-google-pay#7]
Can You add Support for 'DIRECT' Payment Method ?

**Comment by isokolovskii** [comment]
@affanhashone can you provide more detailed description of requested feature with any link to documentation on Google Pay API?

**Comment by leopoldo8** [comment]
https://developers.google.com/pay/api/web/reference/request-objects#direct

**Comment by isokolovskii** [comment]
@leopoldo8 ok, I'll do a research on how to implement it 
Hopes next week I'll have time to implement it

**Comment by leopoldo8** [comment]
Thx

**Comment by syedsarmadkazmi** [comment]
Yes support for 'Direct' method would be great !!
